# Advanced NumPy

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## ndarray Object Internals

In [2]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.ones((10, 5)).shape

(10, 5)

In [4]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

### NumPy dtype Hierarchy

In [5]:
ints = np.ones(10, dtype=np.uint16)
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [6]:
floats = np.ones(10, dtype=np.float32)
floats

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [7]:
np.issubdtype(ints.dtype, np.integer)

True

In [8]:
np.issubdtype(floats.dtype, np.floating)

True

In [9]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [10]:
np.issubdtype(ints.dtype, np.number)

True

## Advanced Array Manipulation

### Reshaping Arrays

In [11]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [13]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [15]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [16]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [18]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C Versus Fortran Order

In [20]:
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [23]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [29]:
arr = np.random.randn(5, 2)
arr

array([[-0.2047,  0.4789],
       [-0.5194, -0.5557],
       [ 1.9658,  1.3934],
       [ 0.0929,  0.2817],
       [ 0.769 ,  1.2464]])

In [33]:
first, second, third = np.split(arr, [2, 3])
first

array([[-0.2047,  0.4789],
       [-0.5194, -0.5557]])

In [34]:
second

array([[1.9658, 1.3934]])

In [35]:
third

array([[0.0929, 0.2817],
       [0.769 , 1.2464]])

#### Stacking helpers: r_ and c_

In [ ]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]
np.c_[np.r_[arr1, arr2], arr]

In [ ]:
np.c_[1:6, -10:-5]

### Repeating Elements: tile and repeat

In [37]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [38]:
arr.repeat(4)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [40]:
arr.repeat([3, 3, 4])

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

In [41]:
arr = np.random.randn(2, 2)
arr

array([[ 1.0072, -1.2962],
       [ 0.275 ,  0.2289]])

In [42]:
arr.repeat(2, axis=0)

array([[ 1.0072, -1.2962],
       [ 1.0072, -1.2962],
       [ 0.275 ,  0.2289],
       [ 0.275 ,  0.2289]])

In [43]:
arr.repeat([2, 3], axis=0)

array([[ 1.0072, -1.2962],
       [ 1.0072, -1.2962],
       [ 0.275 ,  0.2289],
       [ 0.275 ,  0.2289],
       [ 0.275 ,  0.2289]])

In [44]:
arr.repeat([2, 3], axis=1)

array([[ 1.0072,  1.0072, -1.2962, -1.2962, -1.2962],
       [ 0.275 ,  0.275 ,  0.2289,  0.2289,  0.2289]])

In [45]:
arr

array([[ 1.0072, -1.2962],
       [ 0.275 ,  0.2289]])

In [52]:
np.tile(arr, 3)

array([[ 1.0072, -1.2962,  1.0072, -1.2962,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  0.275 ,  0.2289,  0.275 ,  0.2289]])

In [47]:
arr

array([[ 1.0072, -1.2962],
       [ 0.275 ,  0.2289]])

In [48]:
np.tile(arr, (2, 1))

array([[ 1.0072, -1.2962],
       [ 0.275 ,  0.2289],
       [ 1.0072, -1.2962],
       [ 0.275 ,  0.2289]])

In [53]:
np.tile(arr, (3, 2))

array([[ 1.0072, -1.2962,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  0.275 ,  0.2289],
       [ 1.0072, -1.2962,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  0.275 ,  0.2289],
       [ 1.0072, -1.2962,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  0.275 ,  0.2289]])

### Fancy Indexing Equivalents: take and put

In [74]:
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [75]:
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [76]:
arr.take(inds)

array([700, 100, 200, 600])

In [77]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [78]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [81]:
arr.put(inds, [7, 1, 2, 6])
arr

array([  0,   1,   2, 300, 400, 500,   6,   7, 800, 900])

In [82]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438]])

In [71]:
arr.take(inds, axis=1)

array([[-2.0016,  1.3529, -2.0016,  0.8864],
       [-0.5397,  1.669 , -0.5397, -0.4386]])

## Broadcasting

In [86]:
arr1 = np.arange(5)
arr2 = np.arange(5)

In [87]:
arr1

array([0, 1, 2, 3, 4])

In [88]:
arr1 * arr2

array([ 0,  1,  4,  9, 16])

In [89]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [90]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [91]:
arr = np.random.randn(4, 3)
arr

array([[-0.7135, -0.8312, -2.3702],
       [-1.8608, -0.8608,  0.5601],
       [-1.2659,  0.1198, -1.0635],
       [ 0.3329, -2.3594, -0.1995]])

In [92]:
arr.mean(0)

array([-0.8768, -0.9829, -0.7683])

In [93]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 0.1633,  0.1517, -1.6019],
       [-0.9839,  0.1221,  1.3284],
       [-0.3891,  1.1027, -0.2952],
       [ 1.2097, -1.3765,  0.5687]])

In [94]:
demeaned.mean(0)

array([-0.,  0.,  0.])

In [95]:
arr

array([[-0.7135, -0.8312, -2.3702],
       [-1.8608, -0.8608,  0.5601],
       [-1.2659,  0.1198, -1.0635],
       [ 0.3329, -2.3594, -0.1995]])

In [97]:
row_means = arr.mean(1)
row_means

array([-1.305 , -0.7205, -0.7365, -0.742 ])

In [98]:
row_means.shape

(4,)

In [100]:
row_means.reshape((4, 1))

array([[-1.305 ],
       [-0.7205],
       [-0.7365],
       [-0.742 ]])

In [102]:
demeaned = arr - row_means.reshape((4, 1))
demeaned

array([[ 0.5914,  0.4738, -1.0653],
       [-1.1403, -0.1403,  1.2806],
       [-0.5294,  0.8564, -0.327 ],
       [ 1.0749, -1.6174,  0.5425]])

In [103]:
demeaned.mean(1)

array([-0.,  0., -0., -0.])

### Broadcasting Over Other Axes

In [104]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [105]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.5914,  0.4738, -1.0653],
       [-1.1403, -0.1403,  1.2806],
       [-0.5294,  0.8564, -0.327 ],
       [ 1.0749, -1.6174,  0.5425]])

In [106]:
arr = np.zeros((4, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
arr_3d = arr[:, np.newaxis, :]
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [108]:
arr_3d.shape

(4, 1, 4)

In [109]:
arr_1d = np.random.normal(size=3)
arr_1d

array([-1.542 , -0.9707, -1.307 ])

In [110]:
arr_1d[:, np.newaxis]


array([[-1.542 ],
       [-0.9707],
       [-1.307 ]])

In [111]:
arr_1d[np.newaxis, :]

array([[-1.542 , -0.9707, -1.307 ]])

In [115]:
#arr = np.random.randn(3, 4, 5)
arr = np.arange(60).reshape(3, 4, 5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [116]:
depth_means = arr.mean(2)
depth_means

array([[ 2.,  7., 12., 17.],
       [22., 27., 32., 37.],
       [42., 47., 52., 57.]])

In [118]:
depth_means.shape

(3, 4)

In [119]:
depth_means[:, :, np.newaxis]

array([[[ 2.],
        [ 7.],
        [12.],
        [17.]],

       [[22.],
        [27.],
        [32.],
        [37.]],

       [[42.],
        [47.],
        [52.],
        [57.]]])

In [120]:
depth_means[:, :, np.newaxis].shape

(3, 4, 1)

In [121]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [123]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned

array([[[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]],

       [[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]],

       [[-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.],
        [-2., -1.,  0.,  1.,  2.]]])

In [124]:
demeaned.mean(2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

```python
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]
```

### Setting Array Values by Broadcasting

In [125]:
arr = np.zeros((4, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [127]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [128]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [129]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [130]:
arr[:2]

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42]])

In [133]:
np.array([[-1.37], [0.509]])

array([[-1.37 ],
       [ 0.509]])

In [134]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## Advanced ufunc Usage

### ufunc Instance Methods

In [ ]:
arr = np.arange(10)
np.add.reduce(arr)
arr.sum()

In [ ]:
np.random.seed(12346)  # for reproducibility
arr = np.random.randn(5, 5)
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

In [ ]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

In [ ]:
arr = np.arange(3).repeat([1, 2, 2])
arr
np.multiply.outer(arr, np.arange(5))

In [ ]:
x, y = np.random.randn(3, 4), np.random.randn(5)
result = np.subtract.outer(x, y)
result.shape

In [ ]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

In [ ]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr
np.add.reduceat(arr, [0, 2, 4], axis=1)

### Writing New ufuncs in Python

In [ ]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

In [ ]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

In [ ]:
arr = np.random.randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

## Structured and Record Arrays

In [ ]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

In [ ]:
sarr[0]
sarr[0]['y']

In [ ]:
sarr['x']

### Nested dtypes and Multidimensional Fields

In [ ]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

In [ ]:
arr[0]['x']

In [ ]:
arr['x']

In [ ]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']
data['y']
data['x']['a']

### Why Use Structured Arrays?

## More About Sorting

In [ ]:
arr = np.random.randn(6)
arr.sort()
arr

In [ ]:
arr = np.random.randn(3, 5)
arr
arr[:, 0].sort()  # Sort first column values in-place
arr

In [ ]:
arr = np.random.randn(5)
arr
np.sort(arr)
arr

In [ ]:
arr = np.random.randn(3, 5)
arr
arr.sort(axis=1)
arr

In [ ]:
arr[:, ::-1]

### Indirect Sorts: argsort and lexsort

In [ ]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer
values[indexer]

In [ ]:
arr = np.random.randn(3, 5)
arr[0] = values
arr
arr[:, arr[0].argsort()]

In [ ]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter
zip(last_name[sorter], first_name[sorter])

### Alternative Sort Algorithms

In [ ]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
                   '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer
values.take(indexer)

### Partially Sorting Arrays

In [ ]:
np.random.seed(12345)
arr = np.random.randn(20)
arr
np.partition(arr, 3)

In [ ]:
indices = np.argpartition(arr, 3)
indices
arr.take(indices)

### numpy.searchsorted: Finding Elements in a Sorted Array

In [ ]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

In [ ]:
arr.searchsorted([0, 8, 11, 16])

In [ ]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])
arr.searchsorted([0, 1], side='right')

In [ ]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

In [ ]:
labels = bins.searchsorted(data)
labels

In [ ]:
pd.Series(data).groupby(labels).mean()

## Writing Fast NumPy Functions with Numba

In [ ]:
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

```python
In [209]: x = np.random.randn(10000000)

In [210]: y = np.random.randn(10000000)

In [211]: %timeit mean_distance(x, y)
1 loop, best of 3: 2 s per loop

In [212]: %timeit (x - y).mean()
100 loops, best of 3: 14.7 ms per loop
```

```python
In [213]: import numba as nb

In [214]: numba_mean_distance = nb.jit(mean_distance)
```

```python
@nb.jit
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count
```

```python
In [215]: %timeit numba_mean_distance(x, y)
100 loops, best of 3: 10.3 ms per loop
```

```python
from numba import float64, njit

@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()
```

### Creating Custom numpy.ufunc Objects with Numba

```python
from numba import vectorize

@vectorize
def nb_add(x, y):
    return x + y
```

```python
In [13]: x = np.arange(10)

In [14]: nb_add(x, x)
Out[14]: array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [15]: nb_add.accumulate(x, 0)
Out[15]: array([  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.])
```

## Advanced Array Input and Output

### Memory-Mapped Files

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+',
                 shape=(10000, 10000))
mmap

In [ ]:
section = mmap[:5]

In [ ]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap
del mmap

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [ ]:
%xdel mmap
!rm mymmap

### HDF5 and Other Array Storage Options

## Performance Tips

### The Importance of Contiguous Memory

In [ ]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

In [ ]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

In [ ]:
arr_f.copy('C').flags

In [ ]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

In [ ]:
%xdel arr_c
%xdel arr_f

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS