In [1]:
import numpy as np

In [3]:
a = np.random.random((2, 3))

In [4]:
a

array([[0.86367184, 0.35158468, 0.71478632],
       [0.24528766, 0.67691356, 0.33121111]])

In [5]:
a.ravel()
a

array([[0.86367184, 0.35158468, 0.71478632],
       [0.24528766, 0.67691356, 0.33121111]])

In [6]:
a.ravel()

array([0.86367184, 0.35158468, 0.71478632, 0.24528766, 0.67691356,
       0.33121111])

In [7]:
a.reshape(3, 2)

array([[0.86367184, 0.35158468],
       [0.71478632, 0.24528766],
       [0.67691356, 0.33121111]])

In [8]:
a

array([[0.86367184, 0.35158468, 0.71478632],
       [0.24528766, 0.67691356, 0.33121111]])

In [10]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)

In [12]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
np.concatenate((x, y))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [26]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
m = np.array([a, a])
m

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [28]:
m.shape

(2, 3, 2)

In [29]:
m.T

array([[[0, 0],
        [2, 2],
        [4, 4]],

       [[1, 1],
        [3, 3],
        [5, 5]]])

In [30]:
m

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [32]:
a = np.arange(1, 25).reshape((4, 6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [34]:
r = np.hsplit(a, 2)

In [35]:
r

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [36]:
type(r)

list

In [37]:
r[0]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])